server:
  port: 8888

mybatis:
  # 注册mybatis中实体类的别名
  type-aliases-package: com.abc.bean
  # 注册映射文件
  mapper-locations: classpath:mappers/*.xml

spring:
  # 注册数据源
  datasource:
    # 指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaweb?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    username: root
    password: 123456

  # 配置缓存
  cache:
    type: redis # 指定缓存类型
    cache-names: realTimeCache   # 指定缓存区域名称

  # 连接Redis服务器
  redis:
    host: 192.168.0.110
    port: 6379
    password: 123456
  application:
    name: dubbo-provider

# 连接Redis高可有集群
#  redis:
#    sentinel:
#      master: mymaster
#      nodes:
#        - sentinelOS1:26379
#        - sentinelOS2:26379
#        - sentinelOS3:26379

# 指定zk注册中心
dubbo:
  application:
    id: dubbo-provider
    name: dubbo-provider
  registry:
    id: zookeeper-registry
    protocol: zookeeper
    address: zookeeper://192.168.0.105:2181?backup=192.168.0.106:2181,192.168.0.107:2181,192.168.0.108:2181
  metadata-report:
    address: zookeeper://192.168.0.105:2181?backup=192.168.0.106:2181,192.168.0.107:2181,192.168.0.108:2181
  protocol:
    name: dubbo
    port: 20880


