# 功能等价于spring-dubbo配置文件中的<dubbo:application/>
# 指定zk注册中心
dubbo:
  application:
    name: dubbo-consumer
  registry:
    id: zookeeper-registry
    protocol: zookeeper
    address: zookeeper://192.168.0.105:2181?backup=192.168.0.106:2181,192.168.0.107:2181
  monitor:
    protocol: registry

log:
  level:
    com:
      abc: debug

server:
  port: 8081
